"""A single self-contained HTML page summarising a whole batch.

Written for the person who commissioned the work, not the person who ran it:
one row per file, a score bar, and a clear marker on anything that failed.
No external assets, so it opens from an email attachment or a USB stick.
"""

from __future__ import annotations

from html import escape
from pathlib import Path

from app_files.batch.runner import BatchItem, BatchResult


def _score_colour(score: float) -> str:
    if score >= 90:
        return "#047857"
    if score >= 70:
        return "#d97706"
    return "#dc2626"


def _row(item: BatchItem) -> str:
    name = escape(item.file)
    if not item.ok:
        return (
            "<tr>"
            f'<td>{name}</td>'
            '<td><span class="pill bad">failed</span></td>'
            '<td colspan="5" class="muted">'
            f"{escape(item.error or 'unknown error')}</td>"
            "</tr>"
        )
    colour = _score_colour(item.score)
    return (
        "<tr>"
        f'<td>{name}</td>'
        '<td><span class="pill ok">ok</span></td>'
        f"<td class='num'>{item.rows_in:,}</td>"
        f"<td class='num'>{item.rows_out:,}</td>"
        "<td><div class='track'>"
        f"<div class='fill' style='width:{max(0.0, min(100.0, item.score))}%;background:{colour}'></div>"
        "</div></td>"
        f"<td class='num' style='color:{colour};font-weight:600'>{item.score}</td>"
        f"<td class='num'>{item.errors} / {item.warnings}</td>"
        "</tr>"
    )


def render_dashboard(result: BatchResult) -> str:
    """Build the dashboard HTML for a finished batch."""
    rows = "".join(_row(item) for item in result.items)
    if not rows:
        rows = '<tr><td colspan="7" class="muted">No supported files were found.</td></tr>'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Batch dashboard — {escape(result.template)}</title>
<style>
  :root {{ --ink:#111827; --muted:#6b7280; --line:#e5e7eb; --bg:#f9fafb; }}
  * {{ box-sizing: border-box; }}
  body {{ font-family: Inter, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
         color: var(--ink); background: var(--bg); margin: 0; padding: 40px; }}
  .sheet {{ max-width: 1040px; margin: 0 auto; background: #fff; padding: 40px;
            border: 1px solid var(--line); border-radius: 10px; }}
  h1 {{ margin: 0 0 4px; font-size: 24px; }}
  .meta {{ color: var(--muted); font-size: 13px; }}
  .cards {{ display: flex; flex-wrap: wrap; gap: 14px; margin: 22px 0 8px; }}
  .card {{ flex: 1 1 150px; border: 1px solid var(--line); border-radius: 8px; padding: 14px; }}
  .card .value {{ font-size: 24px; font-weight: 600; }}
  .card .label {{ color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: .04em; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 13px; margin-top: 18px; }}
  th, td {{ border-bottom: 1px solid var(--line); padding: 9px; text-align: left; }}
  th {{ background: #f3f4f6; font-weight: 600; }}
  td.num {{ text-align: right; font-variant-numeric: tabular-nums; }}
  .muted {{ color: var(--muted); }}
  .pill {{ display: inline-block; border-radius: 9999px; padding: 2px 10px; font-size: 12px; font-weight: 600; }}
  .pill.ok {{ background: #d1fae5; color: #047857; }}
  .pill.bad {{ background: #fee2e2; color: #b91c1c; }}
  .track {{ background: #f3f4f6; border-radius: 5px; height: 10px; overflow: hidden; min-width: 90px; }}
  .fill {{ height: 100%; border-radius: 5px; }}
</style>
</head>
<body>
<div class="sheet">
  <h1>Batch dashboard</h1>
  <p class="meta">Template <strong>{escape(result.template)}</strong> &middot;
     input <strong>{escape(result.input_dir)}</strong>
     &middot; {result.processed} file(s)</p>
  <div class="cards">
    <div class="card"><div class="label">Files</div><div class="value">{result.processed}</div></div>
    <div class="card"><div class="label">Succeeded</div><div class="value">{result.succeeded}</div></div>
    <div class="card"><div class="label">Failed</div><div class="value">{result.failed}</div></div>
    <div class="card"><div class="label">Rows out</div><div class="value">{result.total_rows_out:,}</div></div>
    <div class="card"><div class="label">Avg score</div><div class="value">{result.average_score}</div></div>
  </div>
  <table>
    <tr><th>File</th><th>Status</th><th>Rows in</th><th>Rows out</th>
        <th>Quality</th><th>Score</th><th>Errors / Warnings</th></tr>
    {rows}
  </table>
  <footer style="color:var(--muted);font-size:12px;margin-top:36px;">
    Generated by DataFlow.</footer>
</div>
</body>
</html>
"""


def write_dashboard(result: BatchResult, path: str | Path, branding=None) -> Path:
    """Write ``dashboard.html``, applying branding when one is supplied."""
    from app_files.branding import inject_branding

    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    html = render_dashboard(result)
    if branding is not None:
        html = inject_branding(html, branding)
    target.write_text(html, encoding="utf-8")
    return target