"""Serve rendered QA reports over HTTP.

NiceGUI element trees travel over a WebSocket, and a full QA report is far
larger than the message limit — embedding it in ``ui.html`` drops the
connection. So a rendered report is published to the session store and fetched
from this route instead, which the results page embeds in an iframe.

Reports are addressed by an unguessable token and content is served as
``text/html`` in a sandboxed iframe. The report is generated by this
application from the user's own upload, so it is not untrusted input in the
way a third-party page would be; the token keeps one client's report from
being read by another.
"""

from __future__ import annotations

from nicegui import app

from app_files.interface.web import session as session_store

_registered: list[bool] = []


def register_report_route() -> None:
    """Mount ``/report/{token}`` on the NiceGUI app, at most once."""
    if _registered:
        return
    _registered.append(True)

    @app.get("/report/{token}")
    def serve_report(token: str):
        from fastapi import Response

        html = session_store.get_report(token)
        if html is None:
            return Response(
                "<!DOCTYPE html><html><body><p>This report is no longer "
                "available. Run the migration again to regenerate it.</p>"
                "</body></html>",
                media_type="text/html",
                status_code=404,
            )
        return Response(html, media_type="text/html")


def report_url(token: str) -> str:
    return f"/report/{token}"