"""One-command deployment manifests for the cloud targets.

This is not a Terraform provider. It generates the files a buyer needs to stand
the service up on a target — a compose file, a Kubernetes manifest, a Render
blueprint — from the same settings the app already reads (the port precedence in
``app_files.settings`` and the two state-home variables).

The one thing it must get right is the port. A platform routes traffic to the
port it injects and reports "no open ports detected" if the container binds
another; the manifest therefore mirrors ``resolve_port`` rather than hardcoding
8080. Getting this wrong is a deploy that fails with a message that points at
networking instead of at the config.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from app_files.settings import DEFAULT_HOST, DEFAULT_PORT

DEPLOY_TARGETS = ("docker", "render", "kubernetes", "render_json")

#: The two state homes every stateful layer reads. A deployment that sets only
#: one leaves the other writing inside the repo.
STATE_HOMES = {"AUTOFLOW_HOME": "/app/run_config", "DATAREADY_HOME": "/app/run_config"}


@dataclass
class DeploymentPlan:
    target: str
    files: dict[str, str] = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)

    def as_dict(self) -> dict:
        return {"target": self.target, "files": sorted(self.files), "notes": list(self.notes)}

    def write(self, directory: str | Path) -> list[Path]:
        directory = Path(directory)
        directory.mkdir(parents=True, exist_ok=True)
        written = []
        for name, content in self.files.items():
            path = directory / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            written.append(path)
        return written


def _env_block(extra: dict[str, str] | None = None) -> dict[str, str]:
    env = dict(STATE_HOMES)
    if extra:
        env.update(extra)
    return env


def deployment_plan(
    target: str,
    image: str = "dataflow:latest",
    port: int = DEFAULT_PORT,
    host: str = DEFAULT_HOST,
    env: dict[str, str] | None = None,
) -> DeploymentPlan:
    """Build the manifest files for one target.

    ``port`` is the port the *service* listens on. The manifests also pass
    ``PORT`` through from the platform when one is present, which is what a PaaS
    injects; a plain host falls back to the value here.
    """
    key = str(target).strip().lower()
    if key not in DEPLOY_TARGETS:
        raise ValueError(
            f"Unknown deploy target {target!r}. Choose one of: {', '.join(DEPLOY_TARGETS)}"
        )
    environment = _env_block(env)

    if key == "docker":
        return _docker(image, port, environment)
    if key in {"render", "render_json"}:
        return _render(image, port, environment)
    return _kubernetes(image, port, environment)


def _docker(image: str, port: int, environment: dict[str, str]) -> DeploymentPlan:
    env_lines = "\n".join(f"      {name}: {value}" for name, value in sorted(environment.items()))
    compose = f"""# Generated by DataFlow. `docker compose up -d`.
services:
  dataflow:
    image: {image}
    restart: unless-stopped
    ports:
      - "${{PORT:-{port}}}:${{PORT:-{port}}}"
    environment:
{env_lines}
    healthcheck:
      test: ["CMD", "python", "-c",
             "import urllib.request,os;urllib.request.urlopen('http://localhost:'+str(os.getenv('PORT',{port}))+'/health')"]
      interval: 30s
      timeout: 5s
      retries: 3
"""
    return DeploymentPlan(
        target="docker",
        files={"docker-compose.yml": compose},
        notes=[
            f"The service binds PORT, falling back to {port}.",
            "Both state homes point at the same volume so every layer writes there.",
        ],
    )


def _render(image: str, port: int, environment: dict[str, str]) -> DeploymentPlan:
    blueprint = {
        "services": [
            {
                "type": "web",
                "name": "dataflow",
                "runtime": "docker",
                "dockerfilePath": "./Dockerfile",
                "plan": "starter",
                # PORT is intentionally absent: Render injects it and routes
                # only there. Setting it here makes the container bind the wrong
                # port and the deploy fails with "no open ports detected".
                "envVars": [{"key": name, "value": value}
                            for name, value in sorted(environment.items())],
                "healthCheckPath": "/health",
            }
        ]
    }
    return DeploymentPlan(
        target="render",
        files={
            "render.yaml": _to_yaml(blueprint),
            "render.json": json.dumps(blueprint, indent=2, sort_keys=True) + "\n",
        },
        notes=[
            "Do not set PORT in render.yaml; render injects it.",
            "Point both state homes at a persistent disk, not the repo tree.",
        ],
    )


def _kubernetes(image: str, port: int, environment: dict[str, str]) -> DeploymentPlan:
    env_lines = "\n".join(
        f"            - name: {name}\n              value: {value!r}"
        for name, value in sorted(environment.items())
    )
    manifest = f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataflow
spec:
  replicas: 1
  selector:
    matchLabels: {{app: dataflow}}
  template:
    metadata:
      labels: {{app: dataflow}}
    spec:
      containers:
        - name: dataflow
          image: {image}
          ports:
            - containerPort: {port}
          env:
{env_lines}
          readinessProbe:
            httpGet: {{path: /ready, port: {port}}}
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: {{path: /health, port: {port}}}
            initialDelaySeconds: 15
          volumeMounts:
            - name: state
              mountPath: /app/run_config
      volumes:
        - name: state
          emptyDir: {{}}
---
apiVersion: v1
kind: Service
metadata:
  name: dataflow
spec:
  selector: {{app: dataflow}}
  ports:
    - port: {port}
      targetPort: {port}
"""
    return DeploymentPlan(
        target="kubernetes",
        files={"dataflow.yaml": manifest},
        notes=[
            f"Readiness probes /ready and liveness /health on port {port}.",
            "Use a PersistentVolumeClaim in place of emptyDir for real state.",
        ],
    )


def _to_yaml(data: dict) -> str:
    """Minimal YAML emitter for the blueprint subset, so no dependency is added."""
    lines: list[str] = []

    def emit(value, indent: int) -> None:
        pad = "  " * indent
        if isinstance(value, dict):
            for key, item in value.items():
                if isinstance(item, (dict, list)):
                    lines.append(f"{pad}{key}:")
                    emit(item, indent + 1)
                else:
                    lines.append(f"{pad}{key}: {_scalar(item)}")
        elif isinstance(value, list):
            for item in value:
                if isinstance(item, dict):
                    first = True
                    for key, sub in item.items():
                        marker = "- " if first else "  "
                        if isinstance(sub, (dict, list)):
                            lines.append(f"{pad}{marker}{key}:")
                            emit(sub, indent + 2)
                        else:
                            lines.append(f"{pad}{marker}{key}: {_scalar(sub)}")
                        first = False
                else:
                    lines.append(f"{pad}- {_scalar(item)}")
        else:
            lines.append(f"{pad}{_scalar(value)}")

    emit(data, 0)
    return "\n".join(lines) + "\n"


def _scalar(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    if text == "" or any(ch in text for ch in ":#{}[],&*?|>-"):
        return json.dumps(text)
    return text


def deploy_manifest(target: str, directory: str | Path, **kwargs) -> list[Path]:
    """Build and write a plan in one call. Returns the paths written."""
    return deployment_plan(target, **kwargs).write(directory)


__all__ = [
    "DEPLOY_TARGETS",
    "STATE_HOMES",
    "DeploymentPlan",
    "deploy_manifest",
    "deployment_plan",
]
